name: example
description: A new Flutter project with the bloc template.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2  
  meta: ">=1.1.0 <2.0.0"
  equatable: ^0.6.1
  flutter_bloc: ^2.0.0  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7

flutter:
  uses-material-design: true